export default {
  NO_CONVERSATION_SIDEBAR: '[data-cy="CI_proMessages_noConversationSidebar"]',
  NO_CONVERSATION_MESSAGES: '[data-cy="CI_proMessages_noConversation"]',
  CONVERSATION_NAME: '[data-cy="CI_proMessages_conversation_name"]',
  CONVERSATION_MESSAGE: '[data-cy="CI_proMessages_conversation_message"]',
  CONVERSATION_SERVICE: '[data-cy="CI_proMessages_conversation_serviceName"]',
  CONVERSATION_UNREAD: '[data-cy="CI_proMessages_conversation_unread"]',
  MESSENGER_REQUEST_DETAILS: '[data-cy="CI_messenger_header_requestDetails"]',
  MESSENGER_CUSTOMER_INFO: '[data-cy="CI_messenger_customerInfo_name"]',
  REQUEST_DETAILS_MAP: '.CI_RequestOverview_RequestDetails_map',
  REQUEST_SECTION_DETAILS:
    '[data-cy="CI_messenger_customerInfo_requestSection"]',
  REQUEST_SECTION_ADDRESS: '[data-cy="CI_messenger_customerInfo_address"]',
  CONVERSATION_CARD:
    '[data-cy="CI_proMessages_conversation-[conversation_id]"]',
  FILTERS_SELECT_ALL: '[data-cy="CI_messenger_filter_selected-all"]',
  FILTERS_STARRED: '[data-cy="CI_messenger_filter_selected-starred"]',
  FILTERS_ARCHIVED: '[data-cy="CI_messenger_filter_selected-archived"]',
  CONVERSATION_STAR: '[data-cy="CI_messenger_header_star"]',
  CONVERSATION_STAR_ALERT: '[data-cy="CI_messenger_alert_star"]',
  CONVERSATION_UNSTAR: '[data-cy="CI_messenger_header_unstar"]',
  CONVERSATION_UNSTAR_ALERT: '[data-cy="CI_messenger_alert_unstar"]',
  CONVERSATION_ARCHIVE: '[data-cy="CI_messenger_header_archive"]',
  CONVERSATION_ARCHIVE_ALERT: '[data-cy="CI_messenger_alert_archive"]',
  CONVERSATION_UNARCHIVE: '[data-cy="CI_messenger_header_unarchive"]',
  CONVERSATION_UNARCHIVE_ALERT: '[data-cy="CI_messenger_alert_unarchive"]',
  ACCEPT_QUOTE: '[data-cy="accept"]',
  DECLINE_QUOTE: '[data-cy="decline"]',
}
