export default {
  ONLINE_APPOINTMENT: '.filters_appointmentType_online',
  EXPERTISE_SHOW_MORE: '.filters_areaOfExpertise_showMore',
  EXPERTISE_SHAPING: '.filters_areaOfExpertise_silhouetteShaping',
  EXPERTISE_YOGA: '.filters_areaOfExpertise_yogaTraining',
  COLLAPSE_ITEM_ACTIVE: '.ant-collapse-item-active',
  FAQ_ITEM0: '.CI_faq_item0',
  FAQ_ITEM1: '.CI_faq_item1',
  FAQ_ITEM2: '.CI_faq_item2',
  FAQ_ITEM3: '.CI_faq_item3',
  FAQ_ITEM4: '.CI_faq_item4',
  FITNESS_TRAINER_AVAILABILITY_ANSWER: '.CI_faq_item0_text',
  FITNESS_TRAINER_PERSONAL_SESSION_ANSWER: '.CI_faq_item1_text',
  FITNESS_TRAINER_PERSONAL_SESSION_PROCESS_ANSWER: '.CI_faq_item2_text',
  FITNESS_TRAINER_LIFESTYLE_QUESTION_ANSWER: '.CI_faq_item3_text',
  FITNESS_TRAINER_CHECK_DOCTOR_ANSWER: '.CI_faq_item4_text',
  FILTER_RATING: '.CI_filters_rating',
  SELECTED_FILTERS_RATING: '.CI_filters_rating_selected',
  FILTERS_PRICE_APPLY: '.CI_filters_price_apply',
  FILTERS_PRICE_MIN: '.CI_filters_price_min input',
  FILTERS_PRICE_MAX: '.CI_filters_price_max input',
  SELECTED_FILTERS_PRICE: '.CI_filter_price',
  EMPTY_LIST_CTA: '.CI_reset_filters',
  FILTERS_APPOINTMENT_TYPE: '.CI_filters_appointment_type',
  AT_MY_LOCATION_INPUT:
    'label.CI_filters_appointment_type_can_travel span input',
  AT_MY_LOCATION_SELECTED: '.CI_filter_travel',
  FILTERS_APPOINTMENT_TYPE_REMOVE: '.CI_filter_travel_clear',
  FILTERS_TIME: '.CI_filters_time',
  FILTERS_TIME_MORNING: '.CI_filters_time_morning',
  FILTERS_TIME_MORNING_IS_CHECKED: '.filters_time_morning__isChecked',
  SELECTED_FILTERS_TIME_MORNING: '.CI_filter_daytimes',
  FILTERS_ACCESSIBILITIES: '.CI_filters_accessibilities',
  ACCESSIBILITIES_ELEVATOR: '.CI_filters_accessibilities_elevator span input',
  ACCESSIBILITIES_ELEVATOR_SELECTED: '.CI_filter_a11y',
  FILTERS_LANGUAGES_SPOKEN: '.CI_filters_languages_spoken',
  LANGUAGES_SPOKEN_FRENCH: '.CI_filters_languages_spoken_fr span input',
  SHOW_MAP_SECTION: '.CI_show_map_button',
  SHOW_MAP_SWITCHER: '.ant-switch',
  ALERT_PRO_WITHOUT_LOCATION: '[data-cy="CI_pro_without_location_message"]',
  ALERT_CLOSE: '.ant-alert-close-icon',
  MAP_SECTION: '.CI_pro_google_map',
  PRO_MARKERS: '[class^="pro-marker-"]',
  MAP_PRO_CARD: '.CI_pro_google_map_card',
  PRO_CARD_LINK: '.CI_procard',
  PRO_CARD_ADD_TO_FAV: '.CI_procard_add_saved',
  PRO_CARD_CTA: '.CI_procard_cta',
  PRO_CARD_PRICE: '.proCard_price',
  TOP_PRO_CTA: '.CI_procard_top_pro',
  PRO_CARD_SAVE_TOOLTIP: '.CI_procard_save_tooltip',
  ANT_TOOLTIP_OPEN: '.ant-tooltip-open',
  PRO_CARD_REMOVE_FROM_SAVED: '.CI_procard_remove_saved',
  PAGINATION: '.ant-pagination',
  PAGINATION_PREV: '.ant-pagination-prev',
  PAGINATION_ITEM_1: '.ant-pagination-item-1',
  PAGINATION_ITEM_2: '.ant-pagination-item-2',
  PRO_CARD: '.CI_procard',
  PRO_CARD_NAME: '.CI_procard_name',
  ANT_PAGINATION_ITEM_ACTIVE: 'ant-pagination-item-active',
  SERVICE_SEARCH_INPUT: '.CI_service_search_input',
  DATE_PICKER: '.CI_search_with_date_picker',
  DATE_PICKER_CALENDAR: '.CI_search_with_date_calendar',
  DATE_PICKER_HEADER: '.ant-picker-header-view',
  DATE_PICKER_HEADER_NEXT: '.ant-picker-header-next-btn',
  DATE_PICKER_HEADER_PREV: '.ant-picker-header-prev-btn',
  DATE_PICKER_TODAY: '.ant-picker-today-btn',
  CITY_SEARCH: '.CI_city_search',
  CITY_SEARCH_INPUT: '.CI_city_search_input',
  MAIN_SECTION: '.CI_listing_title',
  PRO_SEARCH_SUBMIT: '.CI_pro_search_with_date_search',
  SORTING_AVAILABILITY: '.CI_sorting_availability',
  SORTING_PRICE: '.CI_sorting_priceTitle',
  SORTING_RECOMMENDED: '.CI_sorting_recommended',
  SORTING_RATED: '.CI_sorting_rated',
}
