export default {
  CHAT_HEADER_NAME: '[data-cy="CI_messenger_header_name"]',
  CHAT_HEADER_REVIEW_CTA: '[data-cy="CI_messenger_header_leaveReview"]',
  CHAT_HEADER_BACK_BUTTON: '[data-cy="CI_messenger_header_back"]',
  CHAT_INPUT: '[data-cy="message-input"]',
  CHAT_INPUT_CTA: '[data-cy="send-button"]',
  CHAT_CONTENT: '[data-cy="CI_messenger_messages"]',
  CHAT_SEE_PROJECT_DETAILS: '[data-cy="CI_messenger_chat_details"]',
  CHAT_PROJECT_DETAILS_MODAL:
    '[data-cy="CI_RequestOverview_RequestDetails_modal"]',
  CHAT_PROJECT_DETAILS_CTA:
    '[data-cy="CI_RequestOverview_RequestDetails_modal_close"]',
  CHAT_QUICK_REPLY_SECTION: '[data-cy="CI_messenger_quickReply"]',
  CHAT_QUICK_REPLY_SEE_MORE_CTA: '[data-cy="CI_messenger_quickReply_showMore"]',
  CHAT_QUICK_REPLY_NEXT_STEP: '[data-cy="CI_messenger_quickReply_next_step"]',
  SIDEBAR_PRO_INFO: '[data-cy="CI_messenger_proInfo"]',
  SIDEBAR_PROFILE_LINK: '[data-cy="CI_messenger_proInfo_redirectToProfile"]',
  SIDEBAR_REVIEWS_LIST: '[data-cy="CI_messenger_proInfo_reviewsList"]',
  SIDEBAR_REVIEWS_CTA: '[data-cy="CI_messenger_proInfo_reviewsProfileLink"]',
  SIDEBAR_PHOTOS_AND_VIDEOS: '[data-cy="CI_messenger_proInfo_mediaSection"]',
  SIDEBAR_DESCRIPTION: '[data-cy="CI_messenger_proInfo_bioSection"]',
  SIDEBAR_DESCRIPTION_CTA: '[data-cy="CI_messenger_proInfo_bioLinkToProfile"]',
  SIDEBAR_CUSTOMER_INFO: '[data-cy="CI_messenger_customerInfo_section"]',
  SIDEBAR_SERVICE_NAME: '[data-cy="CI_messenger_customerInfo_serviceName"]',
  SIDEBAR_REQUEST_MAP: '[data-cy="CI_messenger_customerInfo_map"]',
  SIDEBAR_REQUEST_FOOTER:
    '[data-cy="CI_messenger_customerInfo_requestFooterSection"]',
  SIDEBAR_APPOINTMENTS_ITEM: '[data-cy="CI_appointmentsList_item"]',
  SIDEBAR_APPOINTMENTS_CONFIRM: '[data-cy="CI_appointmentsList_item_confirm"]',
  SIDEBAR_APPOINTMENTS_DETAILS: '[data-cy="CI_appointmentsList_item_details"]',
  SIDEBAR_CUSTOMER_NAME: '[data-cy="CI_messenger_customerInfo_name"]',
  SIDEBAR_CUSTOMER_ADDRESS: '[data-cy="CI_messenger_customerInfo_address"]',
  SIDEBAR_REVIEW_CTA: '[data-cy="CI_messenger_proInfo_redirectToLeaveReview"]',
  SIDEBAR_PREFER_MESSAGES: '[data-cy="CI_proLeads_lead_prefersMessage"]',
  SIDEBAR_NOCONVERSATION: '[data-cy="CI_proMessages_noConversationSidebar"]',
  SIDEBAR_PROJECT_TAB_SERVICE_NAME:
    '[data-cy="CI_messenger_customerInfo_serviceName"]',
  SIDEBAR_APPOINTMENTS_TAB_CONTENT:
    '[data-cy="CI_appointmentsList_group-upcoming"]',
  SIDEBAR_UPCOMING_APPOINTMENT_ITEM: '[data-cy="CI_appointmentsList_item"]',
  ATTACHMENT_ICON: '[data-cy="CI_messenger_form_addAttachment"]',
  ATTACHMENTS_LIST: '[data-cy="CI_messenger_attachmentsList"]',
  ATTACHMENT_DELETE: '[data-cy="CI_messenger_attachmentsList_item[0]_delete"]',
  ATTACHMENT_LIST_ITEM: '[data-cy="CI_messenger_attachmentsList_item[index]"]',
  CONVERSATION: '[data-cy="CI_userMessages_conversation-[conversation_id]"]',
  CONVERSATION_SIDE_BAR: '[data-cy*="CI_proMessages_conversation-"]',
}
